package com.jc.mod26.main;

public class TrainingTxts {
	
	
	public static String txt1 = "MFEULIFZQTPVVWWNJQARSUAZVJDNEVMGCJPEDYIDCKEEAWBZQEJAXOUFAKBNWBHDURGJOQXPZECJVUDXDORBJHQEJF";
	
	public static String txt2 = "RCPOOTIZBBMKKMBRUEOUVTVCIRMQTOXLYCCEDCCVDGCSCVKOJXEJTBNMULQFPOJAZJKFIEIPPTBBPJEBGRYUJBGODF";
	
	
	
}
