package com.oly.web;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.nio.CharBuffer;

public class LocalCacher {
	
	//SHIFT OF 20
	public static final String exampleSolution = "WBULF CYCNQ UMNBY NSJIC HLUNC FCHYM NBUNA UPYCN UQUSC NUJJY ULYXV INBCH NBYNS JYXGY MMUAY MQYJC WEYXO JUHXC HNBYN LUHMW LCJNI ZNBYL UXCIG YMMUA YJLYN NSOHF CEYFS WICHW CXYHW YMICZ CAOLY SIOLD OHCIL WCJBY LWFYL EQUMC HPIFP YXGCA BNVYQ ILNBW BYWEC HABYL VUWEA LIOHX UHXVU HEUWW IOHNM NBUNC MUFFC GYUHN QBYHC MUCXN BYMIO LWYQU MWFIM YNIBI GYVON NBCHE CHAUV IONCN CUGHI NMOLY CNGUE YMMYH MYNIN BCHEM BYQUM NBYMI OLWYN BYGYM MUAYM MNCFF EYYJW IGCHA UHXCU GAOYM MCHAN BUNMB YBUMA IHYMI NBYLY GOMNV YMIGY INBYL MIOLW YZILI OLCHN YFFCA YHWYM IGYNB CHACM VINBY LCHAG YUVIO NNBYN IHYIZ NBYGY MMUAY MQBSX IYMIO LUHNU AIHCM NEYYJ NUOHN CHAOM UVION IOLUF FCYMC NCMHI NFCEY NBYNB CHAMQ YULYV YCHAU MEYXN IVCXZ ILULY NBCHA MQYUL YFCEY FSNIB CXYZL IGIHY UHINB YLUZN YLUFF UHSQU SCZIF FIQYX IHYIZ IOLZL YHWBW IFFYU AOYMN IZLCY XLCWB MNLUM MYUHX QUNWB YXBYL NLSNI JCWEO JNBYE YSZLI GFIWE YLMYY GMNIB UPYVY YHUWI HCWIO FXHNW FYULF SMYYQ BUNQU MAICH AIHVO NMBYX CXHNM YYGNI VYUVF YNIIJ YHFIW EYLUH XFYZN IVPCI OMFSO JMYNU ZNYLM BYBUX AIHYC NIIEU FIIEU NFIWE YLCNB UMUZU FMYVU WEMIC UGAOY MMCHA NBYGI HYSQU MNUEY HVONH INBCH AJLIP CXYXC HYRWB UHAYW IOFXS IOXCA ULIOH XQCNB SIOLW IHNUW NMCHN BYVLC NCMBU HXLOM MCUHY GVUMM CYMUH XMYYC ZNBYS ULYAY NNCHA NBYMU GYMIL NIZWI GGOHC WUNCI HMGUS VYSIO WIOFX QULHN BYGVS NBYQU SXCYU FWBYG CMNYH JLIDY WNQUM NBYWI XYHUG YZILN BYHUT CUNIG VIGVY ZZILN CBUXU LOHCH QCNBN BYGXO LCHAN BYQUL QBYHQ YQYLY NLSCH ANIEY YJNBY CLBUH XMIZZ NBYBY UPSQU NYLMO JJFSL YGYGV YLNBY VIGVC HACHP YGILE NBUNQ UMOMI LLUNB YLIOL HILXC WUFFC YMUHS QUSCN CMMNC FFNIJ MYWLY NMINB YZUWN IOLJL INUAI HCMNE HIQMU VIONC NCMMC AHCZC WUHNC MOMJY WNNBY EYSNI NBCMQ BIFYG SMNYL SFCYM CHNBY CLCXY HNCNS CZQYE HYQQB INBYS QYLYQ ILECH AZILQ YGCAB NVYUV FYNIZ CAOLY IONQB UNNBY SULYO JNIIH YFUMN NBCHA UWNCH AIHUB OHWBC NIIEU FIIEU NMIGY IZNBY ZLYHW BXYUX XLIJM UZNYL NBYZL CYXLC WBMNL UMMYC HWCXY HNUHX ZIOHX NBYUN NUWBY XWIGG OHCWU NCIHC BUPYH NBUXN CGYNI WLUWE CNVON CNBCH ECNGU SVYUP CAYHY LYUAU CHVON CBUPY HNBUX UWBUH WYNIN LSVUV VUAYM NLCWE IHCNS YNACP YCNNI SIOLV FUWEW BUGVY LUHXM YYQBU NNBYS WUHGU EYIZC NUFFN BYVYM NBULL S";
	
	
	public static boolean hasCache(int num,char T) {
		return getCacheFile(num, T).exists();
	}
	
	public static String getCache(int num,char T) {
		try{
			File file = getCacheFile(num,T);
			FileReader fread = new FileReader(file);
			CharBuffer buff = CharBuffer.allocate(2048);
			fread.read(buff);
			fread.close();
			char[] array = buff.array();
			String output = "";
			for(int i = 0; i < buff.position(); i++) {
				output = output + array[i];
			}
			return output;
		}catch(Exception e) {
			System.err.println("[CACHER] Error reading file cache");
			e.printStackTrace();
			return null;
		}
	}
	
	public static void saveCache(int num,char T,String cache) {
		try{
			File file = getCacheFile(num,T);
			FileWriter fwrite = new FileWriter(file);
			fwrite.write(cache);
			fwrite.close();
		}catch(Exception e) {
			System.err.println("[CACHER] Error saving file cache");
			e.printStackTrace();
		}
	}
	
	
	private static File getCacheFile(int num,char T) {
		File file =  new File("caches\\CyCache_"+num+"_"+T+".cache");
		//file.mkdirs();
		return file;
	}
	
}
